### ISSUE TITLE
[!] tfp0 read failed (os/kern) invalid address addr: 0xa681d35320003e9 err:1 port:ddc103\

### ISSUE THREAD

**Issue by SeaJae** [GeoSn0w/Osiris-Jailbreak#1]
Hi
Seems to fail after I click Jailbreak.  Then the phone reboots.  Iphone 8 global / ios 11.1.3

I'm seeing errors like this in xcode 

[!] tfp0 read failed (os/kern) invalid address addr: 0xa681d35320003e9 err:1 port:ddc103\
[!] tfp0 read failed (os/kern) invalid address addr: 0xa681d35320003ed err:1 port:ddc103\
[!] tfp0 read failed (os/kern) invalid address addr: 0x1 err:1 port:ddc103\

The last few lines in the log before the phone reboots.

v_mount=0x0\
v_flag_location=0x70\
v_flag_value=0x0\
setting v_flag to 0x0\
Found SpringBoard's PID 55\

**Comment by SeaJae** [comment]
When it reboots, the current step on the Phone is “moving stuff”

Also I few times I received a popup on phone stating jailbreak failed please reboot phone.

**Comment by SeaJae** [comment]
It reboots at the step “preparing file system” now.

**Comment by SeaJae** [comment]
I commented out this part 

----------------------------------
//-(void) doAuxStuff{
//    [self.jailbreakMeNowBtn setTitle:@"Preparing File System" forState:UIControlStateDisabled];
//    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 2 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
//        if (yolo() == 0){
//            [self popAShell];
//        } else {
//            [self failure];
//        }
//    });
//}

//- (void) nukeUpdates{
//    [self.jailbreakMeNowBtn setTitle:@"Nuking Apple Update" forState:UIControlStateDisabled];
//    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 2 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
//        disableAutoUpdates();
//        [self popAShell];
//    });
//}

-----------------------------

and I changed line 80 and 81 to this..

------
            //[self doAuxStuff];
                [self popAShell];
-----

Then it works and I get JailBreak successful

is the port for connecting via NC,  the last octet in my phones IP address?

so I would connect to phone via

nc 192.168.11.69 69 

?

**Comment by SeaJae** [comment]
I know technically, all I needed to do was the change to line 80 and 81..

**Comment by Winston-Lin-9527** [comment]
why doesn't Geosnow respond?

**Comment by SeaJae** [comment]
He is probably too busy. I technically didn’t ask any questions.

**Comment by GeoSn0w** [comment]
Switched to dropbear
