### ISSUE TITLE
missing qilin.o for complie

### ISSUE THREAD

**Issue by Zeke0n** [GeoSn0w/Osiris-Jailbreak#11]

**Comment by Lakr233** [comment]
http://newosxbook.com/QiLin/qilin.o

**Comment by Co2333** [comment]
closes #11

**Comment by Co2333** [comment]
Close #11

**Comment by Co2333** [comment]
Closed

**Comment by SeaJae** [comment]
Just copy the QiLin.o file to the main directory that has the Xcode project file. Basically the folder mentioned in the error.
