### ISSUE TITLE
Osiris thinks its remounting FS on 11.3.1 - iPhone 6s 

### ISSUE THREAD

**Issue by hiburn8** [GeoSn0w/Osiris-Jailbreak#16]
Seems like Osiris thinks (presumably incorrectly) that it is remounting the FS on my device and trying to do the 'auxiliary stuff' afterwards. Not sure if this is intentional or a bug in the `if (remountRootFS() == 0){`  check.

**Comment by hiburn8** [comment]
Slightly off topic but feel free to ignore this message... is remounting the FS actually necessary?
Is it not conceivable that we could use the Osiris app's bundle to store jailbreak data rather than remounting the root FS? If we have root privs but cant write to the root FS for whatever reason, surely we could always just read/write data to the jailbreak app storage. We can still manipulate the system in any way we want using the root privs to swizzle stuff in memory right? I'm just not 100% on why we need write access to the root of the FS when we have several places we can write already. In theory, woudnt this allow you to delete a jailbreak and all jailbreak data by deleting the app? That seems like it would be an advantage.
Sorry if this is a dumb question, perhaps I dont fully appreciate what the FS remount does.

**Comment by GeoSn0w** [comment]
Should now be fixed

**Comment by GeoSn0w** [comment]
We need R/W to drop the binaries we need for JB purposes.
