### ISSUE TITLE
Problems building.

### ISSUE THREAD

**Issue by Fuwordy** [GeoSn0w/Osiris-Jailbreak#17]
Your development team, "Donovan Bell", does not support the Multipath capability.
Cannot create a iOS App Development provisioning profile for "com.mid66".
Your development team, "Donovan Bell", does not support the Multipath capability.
No profiles for 'com.mid66' were found
Xcode couldn't find any iOS App Development provisioning profiles matching 'com.mid66'.

**Comment by iHateRa1n** [comment]
Well duh; you don't have a Distribution certificate.

**Comment by Fuwordy** [comment]
The thing is I do.

**Comment by timonline** [comment]
You need to change the bundle identifier to any name unique to you

**Comment by hiburn8** [comment]
@timonline  I knew what you meant, but its not actually the profile name that needs changing, its just the bundle identifier for the app. Just being clear incase anyone else is still stuck. You may also have to remove the line with the `FuckDropbear.h` import.

**Comment by timonline** [comment]
@hiburn8 yes that's what i meant, corrected it in my previous comment.

Also the latest version has the "FuckDropbear.h" removed

**Comment by GeoSn0w** [comment]
Oops. Switched to dropbear and forgot to remove one of the header imports.

**Comment by GeoSn0w** [comment]
@Fuwordy You also need to go to capabilities and toggle Multi Path in Xcode. It is not enough to have the account.

**Comment by lhaasper** [comment]
Not Working for me
