### ISSUE TITLE
get [!] fork() error: Interrupted system call 

### ISSUE THREAD

**Issue by 0neday** [GeoSn0w/Osiris-Jailbreak#4]
fork() failed in fuckdropbear.c

2018-06-13 09:05:37.344575 yalu102[209:3585] enabled patches

2018-06-13 09:05:37.380470 yalu102[209:3585] remounting: 0

2018-06-13 09:05:37.520848 yalu102[209:3585] pid = d7

Finished unzip bootstrap.tar in /tmp 

[!] fork error: Interrupted system call

**Comment by GeoSn0w** [comment]
WTF? yalu102?

**Comment by 0neday** [comment]
@GeoSn0w  just use yalu code

**Comment by GeoSn0w** [comment]
What has yalu to do with this?

**Comment by 0neday** [comment]
@GeoSn0w Yeah, I use  `void do_bind_shell(char* env, int port)` to get shell by mach_portal written by ianbeer. but do not know why this fork() error

**Comment by GeoSn0w** [comment]
Switched to Dropbear
