### ISSUE TITLE
Panic reboot at the end of process , mostly at remount or preparing the file system 

### ISSUE THREAD

**Issue by iM4CH3T3** [GeoSn0w/Osiris-Jailbreak#6]
https://pastebin.com/3cSNWBdQ

**Comment by SeaJae** [comment]
I have the same issue.

**Comment by GeoSn0w** [comment]
Would have been more useful if you posted the Xcode debug log...
Anyways it is because iOS 11.3.x doesn't remount yet.

**Comment by iM4CH3T3** [comment]
Wasn’t plugged in to Xcode as I ran Osiris. But yeah already thought it’s because if the remount issue...

**Comment by GeoSn0w** [comment]
How did you run Osiris without Xcode?

**Comment by iM4CH3T3** [comment]
I installed on the device with Xcode , unplugged and then launched the app and ran jb

**Comment by Dave1482** [comment]
Can confirm this is sometimes how I run all empty_list forks

**Comment by Lakr233** [comment]
Not caused by remount but just VFS bug.
