### ISSUE TITLE
NETCAT nc error

### ISSUE THREAD

**Issue by SeaJae** [GeoSn0w/Osiris-Jailbreak#7]
after the jailbreak succeeds the nc command throws this error.

nc 192.168.11.69 69

The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.objc[322]: +[UIAlertController initialize] may have been in progress in another thread when fork() was called.objc[322]: +[UIAlertController initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

**Comment by GeoSn0w** [comment]
what Xcode version?

**Comment by SeaJae** [comment]
xcode 9.4 (9F1027a)

**Comment by GeoSn0w** [comment]
Switched to dropbear
