### ISSUE TITLE
Failed read from 0x5a6272302b4d3554 - kr : 0x1 Error - (os/kern) invalid address

### ISSUE THREAD

**Issue by iambenmitchell** [GeoSn0w/Osiris-Jailbreak#8]
Works fine until `Bitch-Slapping AMFI` 

Full log: https://pastebin.com/SJJPhzBZ

**Comment by GeoSn0w** [comment]
You are trying it on iOS 11.3.x when I clearly said that remounting doesn't work on iOS 11.3.x yet...
